### ISSUE TITLE
write units in SDDS file

### ISSUE THREAD

**Issue by wei0852** [nikitakuklev/pysdds#1]
Hello, thank you for your code. It really helped me a lot.

I'm trying to write a sdds file for the generalized gradient expansion in ELEGANT.
But ELEGANT cannot work without the units:
```
Problem with column B_rho: wrong units--expected T (?)
Error: unable to read input file
```
Could you please tell me how to set the units of columns?
Thank you very much.

**Comment by nikitakuklev** [comment]
Hey! To set units you need to modify the namelist of the Column (or specify this upon creation).

For example,
`sdds.column_dict['z'].nm['units'] = 'm'`

I updated write demo notebook (and will probably streamline this in the future)

**Comment by wei0852** [comment]
> Hey! To set units you need to modify the namelist of the Column (or specify this upon creation).
> 
> For example, `sdds.column_dict['z'].nm['units'] = 'm'`
> 
> I updated write demo notebook (and will probably streamline this in the future)

Thank you.
